language: go

go:
  - 1.2
  - 1.3
  - 1.4

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get gopkg.in/check.v1

script:
  - go test -v ./... -check.v -check.b
  - ./test-coverage.sh
