language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

matrix:
  allow_failures:
    go: tip

install:
  - sudo apt-get install -qq bzr mercurial git
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/mattn/goveralls
  - go get -u gopkg.in/check.v1
  - go get -d ./...

script:
  - go vet ./...
  - go test -v -race ./... -check.v
  - go test -v ./... -check.v -check.b
  - ./test-coverage.sh
